name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        name: Build, Lint, Format Check, and Test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Bun
              uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Check formatting
              run: bun run format:check

            - name: Lint code
              run: bun run lint

            - name: Build project
              run: bun run build

            - name: Test
              run: bun run test
